useTabs: true
trailingComma: none
arrowParens: avoid
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
svelteStrictMode: true
importOrderSeparation: false
importOrderSortSpecifiers: true
